### ISSUE TITLE
New Version Version: 2023.3.0 Unable to import the csv of keepassX, there is no response after clicking.

### ISSUE THREAD

**Issue by inetclouds** [dani-garcia/vaultwarden#3646] opened 2023-07-04 11:42 UTC
New Version Version: 2023.3.0 Unable to import the csv of keepassX, there is no response after clicking.

**Comment by BlackDex** [comment] 2023-07-04 11:47
Duplicate of #3647

**Closed by BlackDex** 2023-07-04 11:47 UTC
