### ISSUE TITLE
error when moving item to vault "Organization mismatch. Please resync the client before updating the cipher"

### ISSUE THREAD

**Issue by catdevnull** [dani-garcia/vaultwarden#3770] opened 2023-08-13 13:11 UTC
### Subject of the issue

when trying to add an item to a new organization, an error that says "Organization mismatch. Please resync the client before updating the cipher" appears (like #346)

even after restarting, the same thing happens
### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.29.1
* Web-vault version: v2023.5.0
* OS/Arch: linux/x86_64
* Running within Docker: true (Base: Debian)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.41.2
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** DOMAIN, ADMIN_TOKEN

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://*******************",
  "domain_origin": "*****://*******************",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Sutty",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 100000,
  "push_enabled": false,
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": true,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": true,
  "smtp_from": "*********************",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": "***************",
  "smtp_password": "***",
  "smtp_port": 465,
  "smtp_security": "force_tls",
  "smtp_ssl": true,
  "smtp_timeout": 15,
  "smtp_username": "*********************",
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": true,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

* Install method: Docker

* Clients used: Web vault 

* Reverse proxy and version: Caddy 2

### Steps to reproduce

1. create a new organization
2. try to move an item from the user vault to the org vault

### Expected behaviour

it works

### Actual behaviour

it shows this error

![image](https://github.com/dani-garcia/vaultwarden/assets/86896666/cd18ca3c-6c24-4dfc-9877-6cb70d943be3)

### Troubleshooting data

```
config-vaultwarden-1  | [2023-08-13 13:02:11.351][request][INFO] PUT /api/ciphers/REDACTED UUID/share
config-vaultwarden-1  | [2023-08-13 13:02:11.358][vaultwarden::api::core::ciphers][ERROR] Organization mismatch. Please resync the client before updating the cipher
config-vaultwarden-1  | [2023-08-13 13:02:11.358][response][INFO] (put_cipher_share) PUT /api/ciphers/<uuid>/share => 400 Bad Request
```

**Comment by BlackDex** [comment] 2023-08-13 13:24
Have you tried to logout and login again?

**Comment by catdevnull** [comment] 2023-08-13 13:32
yes, the same error appears.

**Comment by BlackDex** [comment] 2023-08-13 14:29
According to the error the UUID of the organization is not valid compared to the data posted.
Try to use the Browsers Dev Console (F12) and see if the Posted data, and then in particular the `organizationId` in the `cipher` tree if that matches or is correct with the organization uuid you want it to move to.

It seems to actually say that the specific cipher already is assigned to an other organization. And moving from one org to an other is not possible.

Not sure how that cipher which is in your own vault is registered in the database, but that should then contain an org uuid already. And that is what makes it break currently.

I just tried the steps, and it works just fine for me.

**Comment by catdevnull** [comment] 2023-08-13 14:57
well, the organizationId does appear to match. 
>And moving from one org to an other is not possible.

i guess this is what's going wrong. why is it not possible? sounds like a bug

**Comment by BlackDex** [comment] 2023-08-13 15:26
Moving from one org to an other isn't possible at all. I think  you are trying to use the `selectable` menu at the top right to just move one (or more) item(s). That will only work for personal items, not for other organizational items.

You need to clone the items instead of moving them.

So, this is by design.

**Closed by BlackDex** 2023-08-13 15:26 UTC
