### ISSUE TITLE
Error - Login with device

### ISSUE THREAD

**Issue by EndMove** [dani-garcia/vaultwarden#3869] opened 2023-09-08 20:42 UTC
To be quick and simple, the request is sent to the phone (latest version android client -> 2023.8.0-7466), but when the request is accepted, the server handles the response wrongly and isn't able to parse it. Server also latest version -> 1.29.2.

Log :
```
[2023-09-08 22:37:35.638][vaultwarden::api::core::accounts::_][WARN] Data guard `Json < AuthResponseRequest >` failed: Parse("{\"key\":\"4.KWr6poiCc68af8qtJtMhxx+QLPJ/atypTGWs659tvnlbvTEKVyru9GLROMbaJD9MeD/eHZMTfiSy0OKmwOtUviivJAnodtT1OjuLAtbDee3/hQgSENDFjMqK363YNLpf+juv2s2nWZ73c5ewIPuNc0Jorg+3w22ycKTu9GkoA+YgNaDbKzF8nSkL08qchAQdzpr5/YUZB2E+S+Hv894vUK87h8lZuvkKzZo8/U1x/PYVTZWctIySpvCMQFUVmTANPf938tBl/FBbewcqBBgpw1JHSz9MmriSNsiRNLq3W1pYbvwdrJ8eA6IfztEAdy8F9gKptz96TSdp7Esv2Q2F8Q==\",\"masterPasswordHash\":null,\"deviceIdentifier\":\"5f872583-3c06-41c5-8e0b-c2781411f4be\",\"requestApproved\":true}", Error("invalid type: null, expected a string", line: 1, column: 381)).
```

**Comment by BlackDex** [comment] 2023-09-08 20:47
Duplicate of:
 1. #3819 
 2. #3862
 3. #3825

Already fixed via: #3831

**Closed by BlackDex** 2023-09-08 20:47 UTC
