### ISSUE TITLE
"t is null error" Vaultwarden + AD

### ISSUE THREAD

**Issue by ptzetaa** [dani-garcia/vaultwarden#3737] opened 2023-07-31 12:22 UTC
### Subject of the issue
I sync my vaultwarden with AD using Bitwarden Directory Connector but when i try to confirm a user "t is null" error appears . 

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.29.1
* Web-vault version: v2023.5.0
* OS/Arch: linux/x86_64
* Running within Docker: true (Base: Debian)
* Environment settings overridden: true
* Uses a reverse proxy: false
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: false
* HTTPS Check: false
* Database type: SQLite
* Database version: 3.41.2
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** ADMIN_TOKEN

```json
{
  "_duo_akey": null,
  "_enable_duo": true,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "****://************************",
  "domain_origin": "****://************************",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": "/data/vaultwarden.log",
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 600000,
  "push_enabled": false,
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": true,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": null,
  "smtp_password": null,
  "smtp_port": 587,
  "smtp_security": "starttls",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": null,
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": false,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

* vaultwarden version: latest

* Install method: docker image

* Clients used:  web vault

* Reverse proxy and version: 

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details:

### Steps to reproduce
 Sync AD with vaultwarden, go to the org, try to confirm an user

### Expected behaviour
 confirm users

### Actual behaviour
 "t is null" error displayed

### Troubleshooting data
 no error logs

**Comment by BlackDex** [comment] 2023-07-31 12:33
There should be some logs report this.
Try to set the log_level to debug and try again.

Without some useful logs I'm afraid we can't reproduce it correctly or know where to look at all.

**Comment by ptzetaa** [comment] 2023-07-31 12:39
How can i set the log level?

**Comment by BlackDex** [comment] 2023-07-31 12:40
Configure the env variable `LOG_LEVEL=debug`

**Comment by ptzetaa** [comment] 2023-07-31 12:44
I dont know if ive done it good but im getting only this:
[2023-07-31 12:42:46.842][start][INFO] Rocket has launched from https://0.0.0.0:80
[2023-07-31 12:42:51.877][request][INFO] GET /api/config
[2023-07-31 12:42:51.878][response][INFO] (config) GET /api/config => 200 OK
[2023-07-31 12:42:51.917][request][INFO] POST /identity/connect/token
[2023-07-31 12:42:51.926][response][INFO] (login) POST /identity/connect/token => 200 OK
[2023-07-31 12:42:51.957][request][INFO] GET /api/sync?excludeDomains=true
[2023-07-31 12:42:51.960][response][INFO] (sync) GET /api/sync?<data..> => 200 OK
[2023-07-31 12:42:52.009][request][INFO] GET /api/config
[2023-07-31 12:42:52.010][response][INFO] (config) GET /api/config => 200 OK
[2023-07-31 12:42:55.742][request][INFO] GET /api/organizations/5f1201a2-6aa5-4260-8fb5-cf60e92e2db5/users?includeCollections=true
[2023-07-31 12:42:55.747][response][INFO] (get_org_users) GET /api/organizations/<org_id>/users?<data..> => 200 OK
[2023-07-31 12:42:55.750][request][INFO] GET /api/organizations/5f1201a2-6aa5-4260-8fb5-cf60e92e2db5/collections
[2023-07-31 12:42:55.752][response][INFO] (get_org_collections) GET /api/organizations/<org_id>/collections => 200 OK
[2023-07-31 12:42:55.753][request][INFO] GET /notifications/hub?access_token=eyJ0eXAiOiJKV1QiL
[2023-07-31 12:42:55.753][vaultwarden::api::notifications][INFO] Accepting Rocket WS connection from 172.16.150.89
[2023-07-31 12:42:55.754][response][INFO] (websockets_hub) GET /notifications/hub?<data..> => 200 OK
[2023-07-31 12:42:57.474][request][INFO] GET /api/users/c6cd01a5-5e03-46c7-8e6d-fee127c615e8/public-key
[2023-07-31 12:42:57.476][response][INFO] (get_public_keys) GET /api/users/<uuid>/public-key => 200 OK

**Comment by BlackDex** [comment] 2023-07-31 13:04
But now we need the logs during the time you get the error because these logs do not seem to contain anything in regards to confirming a user.

**Comment by BlackDex** [comment] 2023-07-31 15:04
I quickly tested this again, and it works just fine. So, unless you can provide some more logs which shows an error, or maybe browser error's via F12 Developer Console, I think this is a configuration issues on your side.

I see that the Admin panel shows a Domain issue, that could be because you access the admin page internally, but it could also mean configuration issues. And I see it complains on HTTPS, if you did not used HTTP, that could cause issues as well, the web-vault is not designed to be access without HTTPS (unless accessed via localhost).

**Comment by stefan0xC** [comment] 2023-07-31 15:30
@ptzetaa I think the users don't actually exist und they'll have to create an account before you can confirm them.

@BlackDex Can you test this without SMTP enabled? I think the issue might be that the users are accepted in the `import` function so they show up even though they shouldn't:
https://github.com/dani-garcia/vaultwarden/blob/3dbfc484a54c41d1759646444b439da06445060b/src/api/core/organizations.rs#L1893-L1900

I believe there is a check missing because the `User::find_by_email()` function will find invited "Users" too where `user.password_hash.is_empty()`

**Comment by BlackDex** [comment] 2023-07-31 18:22
@stefan0xC, that is actually the wrong endpoint you were looking at ;).
We need to do some chores in regards to cleanup old code I think (But that could break environments using that endpoint).

Also looking at the code above and other parts, i actually think we need to changes more stuff to consolidate this all a bit more.
Now we create users and org-users in several places in different ways which doesn't make it better and more error prone i think.

**Comment by BlackDex** [comment] 2023-07-31 18:50
@ptzetaa Fix created and i tested the same setup, and it seems to work now.

Thanks for the report!

**Comment by ptzetaa** [comment] 2023-08-01 06:10
Thanks mate! Im going to try it

**Comment by BlackDex** [comment] 2023-08-01 08:16
There is no new image yet. There is a PR open which needs to be merged before it will build a new `testing` image.

Passwords can not be synced, the format is not the same, and Bitwarden needs an actual password.
The Directory Connector only manage the users by creating or removing them, and adding them to groups (if enabled).
Users will then, if enabled, receive an invite mail and once registered they need to be confirmed, and after that they are able to access the Org vault.

**Comment by ptzetaa** [comment] 2023-08-01 08:27
Okay thanks

**Closed** 2023-08-12 20:19 UTC
