### ISSUE TITLE
UI Issues with Large Number of Organizations

### ISSUE THREAD

**Issue by hawkeye426** [dani-garcia/vaultwarden#3052] opened 2022-12-27 20:54 UTC
Organization vaults are not listed alphabetically under the "All Vaults" menu on the left sidebar within the "Vaults" page, and  the organization list on the "Organizations" page (from clicking the organization name to change organizations) does not expand to allow for a longer list then the page length, a problem with 20+ organizations.

**Comment by BlackDex** [comment] 2022-12-27 21:04
Duplicate of #3005 
Also, same as there, these are web-vault issues. Vaultwarden doesn't maintain the actual clients which the web-vault is one of them.

Second, i think Bitwarden isn't designed with 20+ organizations in mind.

**Closed by BlackDex** 2022-12-27 21:04 UTC
