### ISSUE TITLE
Pending login requests Error

### ISSUE THREAD

**Issue by TLSMars-yangtzeu** [dani-garcia/vaultwarden#3948] opened 2023-10-02 14:09 UTC
### Subject of the issue

* **Issue**: When attempting to log in to my self-hosted Vaultwarden server in the Edge browser by using my phone or the Bitwarden Desktop application to handle pending login requests:

  - **Problem**: The login process failed to work as expected.

  - Diagnosis: I resorted to using Bitwarden Desktop's development mode for server debugging.
      - **Discovery**: Surprisingly, the debugging revealed that API requests were failing.
      - **Observation**: No related errors appeared in the Docker logs.

  - **Additional Information**: I have included some screenshots in the troubleshooting section below for further insight into the issue.

### Deployment environment

* vaultwarden version: 1.29.2

* Install method: self-drive vaultwarden/server:latest docker image,  with HTTPS

* Clients used: desktop, android, edge extension,ipad

* Reverse proxy and version: nginx/1.18.0

* MySQL/MariaDB or PostgreSQL version: sqlite3

* Other relevant details:  
### Steps to reproduce

1. Create an account.
2. Log in on one device.
3. Access the "Pending Login Requests" feature.
4. Log in on another device and provide email.
5. Opt for device login instead of entering a password.
6. Observe the pending login requests on any device. 

### Expected behaviour

The "Pending Login Requests" feature should function correctly.

### Troubleshooting data

* error api

  ![1696253475662](https://github.com/dani-garcia/vaultwarden/assets/141105794/b45ede5c-8d6b-4879-89ab-1d4e77239b47)

* requests param

  ![1696253475662](https://github.com/dani-garcia/vaultwarden/assets/141105794/cf0d8f1e-5197-4032-a79e-6ba2d27dbef4)

* respond 

  ![image-20231002213358001](https://github.com/dani-garcia/vaultwarden/assets/141105794/b1b5b9e9-c9cf-49df-9ddc-24d2b1f4513f)

* terminal error

  ![image-20231002213629568](https://github.com/dani-garcia/vaultwarden/assets/141105794/2cf8c461-a748-47f4-86f4-8942da3d1b0d)

* other error

    * WebSocket failed to connect

  ![image-20231002214710009](https://github.com/dani-garcia/vaultwarden/assets/141105794/b5fbdb44-d5b8-4c1e-9e9e-7ed21978bf8d)

    * log file:

        ```
        [2023-10-02 13:12:26.777][vaultwarden::api::core::accounts::_][WARN] Data guard `Json < AuthResponseRequest >` failed: Parse("{\"key\":\"4.sVgxQxxxxxxxxxxxxxxxxxxxxzL/VhpPRXKHj/v1B1JV75QX/6NSQQeKbDB4/xQGjaDdNyrTVO+troIy/6ttkKHnFlt5vHxxxxxxxxxxxxxxxxxxxxcYJHy2p2P1eYx9gIpHlU/upumxxxxxxxxxxxxxxxxxxxxMxCkFfZQRX/zWjISTp0+jSFPYrtUsHH+uIc0E8nNlZiFjOHLxxxxxxxxxxxxxxxxxxxxCGBQcsmZEnkbam7oaHvdweTdd/WFTjnVORqBu8jbOqQcdFbxd/Bd2V5NzQ4SY5+gbeOY7Ir4vAHp1kMaLF4V6aN4A==\",\"deviceIdentifier\":\"7e472838-365b-4344-865f-a82dd344fd61\",\"requestApproved\":true}", Error("missing field `masterPasswordHash`", line: 1, column: 437)).
        ```

​			there is not other error in log file.

**Comment by BlackDex** [comment] 2023-10-02 14:10
Duplicate of many others.
Already fixed in the `testing` tagged images.

**Closed by BlackDex** 2023-10-02 14:10 UTC
