### ISSUE TITLE
JSON Import Error: e.match(...) is null

### ISSUE THREAD

**Issue by ibsga** [dani-garcia/vaultwarden#4007] opened 2023-10-27 09:36 UTC
### Deployment environment
When I try to import, does not matter if JSON or JSON encrypted, I got the error: e.match(...) is null.
CSV Import works just fine.
The Folders are getting imported but no logins.

 

* vaultwarden version:
1.29.2-ecb31c85

* Install method:
Script for Proxmox: https://tteck.github.io/Proxmox/
* Reverse proxy and version: 
Cloudflare Tunnel

### Expected behaviour

I expected to import not just the folders, but also the logins.
### Actual behaviour

Only the Folders are getting imported
### Troubleshooting data

![Screenshot 2023-10-27 113605](https://github.com/dani-garcia/vaultwarden/assets/123656908/2991d229-a353-4956-a596-008183b332a4)

**Comment by ibsga** [comment] 2023-10-27 09:51
I can add that on the official Bitwarden the files are working just fine.

**Comment by BlackDex** [comment] 2023-10-27 11:00
Duplicate of #4005, please add your comments there.

**Closed by BlackDex** 2023-10-27 11:00 UTC
