### ISSUE TITLE
Env-Variable - Renaming SMTP_EXPLICIT_TLS

### ISSUE THREAD

**Issue by sando38** [dani-garcia/vaultwarden#2225] opened 2022-01-11 08:09 UTC
Hello there,

reporting this, because I missinterpreted it. According to RFC8314 (https://datatracker.ietf.org/doc/html/rfc8314#section-3.3) implicit TLS is used for port 465.
However, to force tls with environment variables in the smtp settings, I have to set:

SMTP_EXPLICIT_TLS=true -> which would actually imply STARTTLS.

So, either I suggest renaming the environment variable into:

SMTP_IMPLICIT_TLS or 
SMTP_FORCE_TLS

to avoid confusion.

NB: Thanks for your great service with providing vaultwarden. It is a great tool.

Wishing a nice day!

**Comment by BlackDex** [comment] 2022-01-11 08:22
This will be a wont fix, since this would lead to a lot of invalid configurations. A lot of people have this configured using that variable and we would not like to break those. Also, adding a second variable and keeping the current one will probably lead to confusion or also some weird issues.

There is already a mentioning of the wrongly named variable here: https://github.com/dani-garcia/vaultwarden/blob/main/.env.template#L335

Also see #851 (which this ticket is a duplicate of)

**Closed by BlackDex** 2022-01-11 08:22 UTC
Labels: wontfix
