### ISSUE TITLE
1.29.2 docker image not starting up on Ubuntu 20.04 (x84_64)

### ISSUE THREAD

**Issue by knightsg** [dani-garcia/vaultwarden#3872] opened 2023-09-10 04:50 UTC
### Subject of the issue
After updating to the 1.29.2 image the container continually restarts with the following error (with RUST_BACKTRACE enabled):
```
vaultwarden_1  | thread 'main' panicked at 'OS can't spawn worker thread: Operation not permitted (os error 1)', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.31.0/src/runtime/scheduler/multi_thread/worker.rs:447:13
vaultwarden_1  | stack backtrace:
vaultwarden_1  |    0: rust_begin_unwind
vaultwarden_1  |    1: core::panicking::panic_fmt
vaultwarden_1  |    2: tokio::runtime::blocking::pool::Spawner::spawn_blocking
vaultwarden_1  |    3: tokio::runtime::blocking::pool::spawn_blocking
vaultwarden_1  |    4: tokio::runtime::scheduler::multi_thread::worker::Launch::launch
vaultwarden_1  |    5: tokio::runtime::builder::Builder::build
vaultwarden_1  |    6: vaultwarden::main
vaultwarden_1  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
vwserver_vaultwarden_1 exited with code 101
```

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.29.1
* Web-vault version: v2023.5.0
* OS/Arch: linux/x86_64
* Running within Docker: true (Base: Debian)
* Environment settings overridden: false
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.41.2
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** 

```json
{
  "_duo_akey": "***",
  "_enable_duo": true,
  "_enable_email_2fa": true,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://********************",
  "domain_origin": "*****://********************",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "extended_logging": true,
  "helo_name": null,
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": null,
  "log_level": "Info",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 600000,
  "push_enabled": false,
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": true,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "**************************",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": "****",
  "smtp_password": null,
  "smtp_port": 25,
  "smtp_security": "off",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": null,
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": true,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

* Host system: Ubuntu 20.04.2 LTS

* vaultwarden version: 1.29.1 (rolled back from 1.29.2 after it failed to start) 

* Install method: Docker image (via docker-compose)

* Clients used: web vault, android, iOS

* Reverse proxy and version: nginx 1.25.2

* MySQL/MariaDB or PostgreSQL version: N/A

* Other relevant details:

### Steps to reproduce
I just updated the version of vaultwarden in my docker-compose file as usual and it didn't work; in the container logs it showed the error outlined in the summary above. Once I identified the issue I reverted the version in the docker-compose file back to 1.29.1 and it started up again without problems.

### Expected behaviour
Vaultwarden docker container starts without problems.

### Actual behaviour
Container continually restarted and the container logs showed the error specified above after configuring RUST_BACKTRACE in the environment.

### Troubleshooting data
This may be the same issue as mentioned in https://github.com/dani-garcia/vaultwarden/issues/3839 but as there's no additional detail in that report I can't be sure.

**Comment by BlackDex** [comment] 2023-09-10 05:42
Duplicate of:
1. #3827
2. #3867
3. And a few others

And no, it's not the same as #3839, if that was the case you wouldn't have seen anything.

**Closed by BlackDex** 2023-09-10 05:42 UTC
