### ISSUE TITLE
Persistent data check does not work with volumes

### ISSUE THREAD

**Issue by TymanWasTaken** [dani-garcia/vaultwarden#2633] opened 2022-07-20 04:14 UTC
### Subject of the issue

When using a docker volume, vaultwarden incorrectly determines it to not be persistent storage

### Deployment environment

* vaultwarden version: 1.25.1

* Install method: Docker image

* Clients used: N/A 

* Reverse proxy and version: N/A 

* MySQL/MariaDB or PostgreSQL version: N/A 

* Other relevant details: Docker version 20.10.17

### Steps to reproduce

Attempt to run vaultwarden mounting a docker volume to `/data`, no other configuration changes

### Expected behaviour

Vaultwarden starts fine

### Actual behaviour

Vaultwarden refuses to start without the I_REALLY_WANT_VOLATILE_STORAGE env variable set

### Troubleshooting data

No troubleshooting data, but I believe this is caused because of a difference in how bind mounts work and how volume works. From what I can tell, vaultwarden detects non-persistent storage by creating a file in the dockerimage, and then checking for it on start. However, this is flawed because docker will automatically populate volumes with any files that images create, making that file visible to vaultwarden regardless of the fact that it is actually persistent storage. I temporarily fixed this by just setting I_REALLY_WANT_VOLATILE_STORAGE=true, but it is still a bug that should probably be fixed.

**Comment by BlackDex** [comment] 2022-07-20 05:04
Closing as a duplicate of #2622

**Closed by BlackDex** 2022-07-20 05:04 UTC
