### ISSUE TITLE
Vaultwarden (running in docker on Cloudron) - attachments do not work properly in Organizations but fine in personal account.

### ISSUE THREAD

**Issue by alexdimarco** [dani-garcia/vaultwarden#1982] opened 2021-09-18 21:37 UTC
Uploading an attachment in "My Vault" works without issue. 

If I switch to one of my organizations, creating and uploading a document fails with 
![image](https://user-images.githubusercontent.com/4382150/133908973-3146309c-a0ae-42ba-8a13-dc631e72f4df.png)

Item shows up as present but cannot be downloaded:

![image](https://user-images.githubusercontent.com/4382150/133909152-4c485a11-7c92-4c2a-b5d3-80f5e32c08ed.png)

This is repeatable in every Organisation 

![image](https://user-images.githubusercontent.com/4382150/133909101-31f8e88c-a152-4636-ba3b-35dbd8e4592a.png)

**Comment by alexdimarco** [comment] 2021-09-18 21:44
Workaround - If I create the item and the attachment in "My Vault" and assign it to the organization, it works without a problem, and can be downloaded from within the organization tab.

**Comment by jjlin** [comment] 2021-09-18 21:50
This looks like a duplicate of #1920. The fix (#1922) is not in a released version yet.

**Comment by BlackDex** [comment] 2021-09-18 21:50
This was already fixed and available in the current testing image.

@jjlin fixed this via https://github.com/dani-garcia/vaultwarden/pull/1922

**Closed** 2021-09-18 21:51 UTC
Labels: duplicate
