### ISSUE TITLE
can't start docker container (latest version on docker hub)

### ISSUE THREAD

**Issue by Tom-jm03** [dani-garcia/vaultwarden#2563] opened 2022-06-18 22:26 UTC
### Deployment environment

* vaultwarden version: latest from dockerhub

* Install method: Docker Image

* Clients used: 
 /

* Reverse proxy and version: 
 /

* MySQL/MariaDB or PostgreSQL version: 
/

* Other relevant details:
 /

### Steps to reproduce

i used, yubico, smtp and nothing more with a docker run command

### Expected behaviour

that the container starts without crashing

### Actual behaviour

when trying to start the container with the latest vaultwarden docker image, it instantly crashes and in portainer(a webgui for viewing containers), i see that traceback: (logs.txt)

### Troubleshooting data

[logs.txt](https://github.com/dani-garcia/vaultwarden/files/8934445/logs.txt)
if you do have more questions, please do not hesitate, to ask them

**Comment by BlackDex** [comment] 2022-06-18 22:33
Duplicate of #2497

**Closed by BlackDex** 2022-06-18 22:33 UTC
