### ISSUE TITLE
Managing 2FA in Web UI does not work anymore

### ISSUE THREAD

**Issue by fhibler** [dani-garcia/vaultwarden#4044] opened 2023-11-07 12:50 UTC
### Subject of the issue
Managing 2FA in Web UI does not work anymore

### Your environment (Generated via diagnostics page)
* Vaultwarden version: v1.30.0
* Web-vault version: v2023.10.0
* OS/Arch: linux/x86_64
* Running within Docker: true (Base: Debian)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Forwarded-For)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.41.2
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Steps to reproduce
* Go to your Account Settings -> Security -> Tab 'Two-step login'
* Click to 'Manage' on a 2FA provider (like Email or FIDO2 WebAuthn)
* Click 'Send Code' under 'Send a verification code to your email'
* Red Error popup 'An error has occured - An unexpected error has occurred.' appears on the top right side of the page

The logs of the application server also show this:
```
[2023-11-07 12:47:19.670][request][INFO] POST /api/accounts/request-otp
[2023-11-07 12:47:19.670][response][INFO] 404 Not Found
```

### Expected behaviour
Email with verification code is being sent

### Actual behaviour
Can't manage any 2FA anymore

### Troubleshooting data
![Screenshot 2023-11-07 at 13 48 37](https://github.com/dani-garcia/vaultwarden/assets/1452221/984717a5-ff62-493a-90b3-8ae2b3580fc8)
![Screenshot 2023-11-07 at 13 48 43](https://github.com/dani-garcia/vaultwarden/assets/1452221/089f6abb-e7a7-4d87-a8bf-922f01dbb0b1)

**Comment by BlackDex** [comment] 2023-11-07 13:03
Probably a Duplicate of #4042

**Closed by BlackDex** 2023-11-07 13:03 UTC
