### ISSUE TITLE
v1.29.2 Crashed

### ISSUE THREAD

**Issue by sl33nyc** [dani-garcia/vaultwarden#3992] opened 2023-10-22 21:06 UTC
### Subject of the issue
My vaultwarden instance crashed.

### Deployment environment

Ubuntu arm64

* vaultwarden version:

* Install method: Extracted binary from Docker image.

* Clients used: 

* Reverse proxy and version: 

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details

`dmesg` logging (note that I didn't find other relevant logging):

```
[Sun Oct 22 12:13:54 2023] rocket-worker-t: page allocation failure: order:7, mode:0x40dc0(GFP_KERNEL|__GFP_COMP|__GFP_ZERO), nodemask=(null),cpuset=/,mems_allowed=0
[Sun Oct 22 12:13:54 2023] CPU: 1 PID: 86689 Comm: rocket-worker-t Tainted: P           O      5.15.0-1047-aws #52~20.04.1-Ubuntu
[Sun Oct 22 12:13:54 2023] Hardware name: Amazon EC2 t4g.micro/, BIOS 1.0 11/1/2018
[Sun Oct 22 12:13:54 2023] Call trace:
[Sun Oct 22 12:13:54 2023]  dump_backtrace+0x0/0x210
[Sun Oct 22 12:13:54 2023]  show_stack+0x20/0x30
[Sun Oct 22 12:13:54 2023]  dump_stack_lvl+0x68/0x84
[Sun Oct 22 12:13:54 2023]  dump_stack+0x18/0x34
[Sun Oct 22 12:13:54 2023]  warn_alloc+0x118/0x1a8
[Sun Oct 22 12:13:54 2023]  __alloc_pages_slowpath.constprop.0+0xbc4/0xc20
[Sun Oct 22 12:13:54 2023]  __alloc_pages+0x290/0x308
[Sun Oct 22 12:13:54 2023]  alloc_pages+0xb4/0x158
[Sun Oct 22 12:13:54 2023]  kmalloc_order+0x38/0x118
[Sun Oct 22 12:13:54 2023]  kmalloc_order_trace+0x34/0x190
[Sun Oct 22 12:13:54 2023]  __kmalloc+0x308/0x3b8
[Sun Oct 22 12:13:54 2023]  __regset_get+0xa0/0x108
[Sun Oct 22 12:13:54 2023]  regset_get_alloc+0x1c/0x28
[Sun Oct 22 12:13:54 2023]  fill_note_info+0x358/0x700
[Sun Oct 22 12:13:54 2023]  elf_core_dump+0x6c/0x450
[Sun Oct 22 12:13:54 2023]  do_coredump+0x68c/0xdf8
[Sun Oct 22 12:13:54 2023]  get_signal+0x1a0/0x8e0
[Sun Oct 22 12:13:54 2023]  do_notify_resume+0x2d8/0x7e8
[Sun Oct 22 12:13:54 2023]  el0_da+0x118/0x180
[Sun Oct 22 12:13:54 2023]  el0t_64_sync_handler+0x88/0xb8
[Sun Oct 22 12:13:54 2023]  el0t_64_sync+0x1a4/0x1a8
[Sun Oct 22 12:13:54 2023] Mem-Info:
[Sun Oct 22 12:13:54 2023] active_anon:268 inactive_anon:95514 isolated_anon:0
                            active_file:27075 inactive_file:25350 isolated_file:0
                            unevictable:4251 dirty:127 writeback:0
                            slab_reclaimable:13166 slab_unreclaimable:12635
                            mapped:20010 shmem:348 pagetables:1039 bounce:0
                            kernel_misc_reclaimable:0
                            free:13769 free_pcp:122 free_cma:0
[Sun Oct 22 12:13:54 2023] Node 0 active_anon:1072kB inactive_anon:382056kB active_file:108300kB inactive_file:101400kB unevictable:17004kB isolated(anon):0kB isolated(file):0kB mapped:80040kB dirty:508kB writeback:0kB shmem:1392kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 0kB writeback_tmp:0kB kernel_stack:4976kB pagetables:4156kB all_unreclaimable? no
[Sun Oct 22 12:13:54 2023] Node 0 DMA free:55076kB min:22528kB low:28160kB high:33792kB reserved_highatomic:0KB active_anon:1072kB inactive_anon:381920kB active_file:108300kB inactive_file:101152kB unevictable:17004kB writepending:508kB present:1021952kB managed:960112kB mlocked:17004kB bounce:0kB free_pcp:488kB local_pcp:0kB free_cma:0kB
[Sun Oct 22 12:13:54 2023] lowmem_reserve[]: 0 0 0 0 0
[Sun Oct 22 12:13:54 2023] Node 0 DMA: 3379*4kB (UME) 1073*8kB (UME) 573*16kB (UME) 426*32kB (UME) 143*64kB (UM) 8*128kB (U) 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB 0*8192kB 0*16384kB = 55076kB
[Sun Oct 22 12:13:54 2023] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
[Sun Oct 22 12:13:54 2023] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=32768kB
[Sun Oct 22 12:13:54 2023] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[Sun Oct 22 12:13:54 2023] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=64kB
[Sun Oct 22 12:13:54 2023] 54302 total pagecache pages
[Sun Oct 22 12:13:54 2023] 0 pages in swap cache
[Sun Oct 22 12:13:54 2023] Swap cache stats: add 0, delete 0, find 0/0
[Sun Oct 22 12:13:54 2023] Free swap  = 0kB
[Sun Oct 22 12:13:54 2023] Total swap = 0kB
[Sun Oct 22 12:13:54 2023] 255488 pages RAM
[Sun Oct 22 12:13:54 2023] 0 pages HighMem/MovableOnly
[Sun Oct 22 12:13:54 2023] 15460 pages reserved
[Sun Oct 22 12:13:54 2023] 0 pages hwpoisoned
```

### Troubleshooting data

Please let me know if I should restart with any options to enable more debugging info.

**Comment by ipajumets** [comment] 2023-10-23 07:30
Can confirm this, happening to us as well. Crashing randomly. Can't put a finger on it right now.

**Comment by BlackDex** [comment] 2023-10-23 08:14
Possible duplicate of:
#3912
#3957

Or
#3961

**Closed by BlackDex** 2023-10-23 08:14 UTC

**Comment by iluvatyr** [comment] 2023-11-19 00:44
My vaultwarden crashed too. Dmesg showed this.

```
[Sun Nov 19 01:15:46 2023] rocket-worker-t[866695]: segfault at 633e ip 00007f9f808af5ff sp 00007f9f7e480138 error 4 in vaultwarden[7f9f7ea97000+23d9000] likely on CPU 2 (core 2, socket 0)
```
