### ISSUE TITLE
Upgrade to 1.25.0 resets language preference to "english"

### ISSUE THREAD

**Issue by OdyX** [dani-garcia/vaultwarden#2541] opened 2022-06-08 07:27 UTC
It seems that after upgrading to 1.25.0 (from 1.24.0), the users' language preferences have been forcibly set to "english" instead of "auto"; they all need to navigate to their web client's "Options" and toggle this back to "auto".

### Deployment environment

* Install method: Docker image

* Clients used: web

### Steps to reproduce
It happened on both our "beta" setup, and on our "prod" setup. Upgrade was done with:
```
docker-compose pull
docker-compose up -d --force-recreate
```

### Expected behaviour
The default language should be "auto", not "english".

I don't seem to find a DB column for that preference; where is it stored?

Best,
Didier

**Comment by BlackDex** [comment] 2022-06-08 07:47
Duplicate of #2540

**Closed by BlackDex** 2022-06-08 07:47 UTC
