### ISSUE TITLE
GUI problem with dark design

### ISSUE THREAD

**Issue by XxJooO** [dani-garcia/vaultwarden#2434] opened 2022-04-24 11:54 UTC
Hello, I am using version 2.25.1 of a self-hosted Vaultwarden. There is a dark design error in the GUI. When I choose dark, then in the selection box the font is not matched in color. It uses white on white. I first noticed this when I wanted to move a folder. Under the folders to be selected, the font is also white on white and you can't read anything.

**Comment by BlackDex** [comment] 2022-04-24 11:57
Closing this as a duplicate of #2336 and #2252

**Closed by BlackDex** 2022-04-24 11:57 UTC
