### ISSUE TITLE
Manager user cannot manage users or collections

### ISSUE THREAD

**Issue by chrpinedo** [dani-garcia/vaultwarden#2239] opened 2022-01-17 12:03 UTC
### Subject of the issue
User with "manager" role cannot manage the users and collections of one organization.

The manager user can see the manage tab of the organization but as soon as it clicks on it, it gets one error and he is logged out.

### Deployment environment

* vaultwarden version: 1.23.1

* Install method: docker

* Clients used: web vault

* Reverse proxy and version: nginx 1.20.2

* MySQL/MariaDB or PostgreSQL version: (internal sqllite database)

* Other relevant details:

### Steps to reproduce
Use a "manager" user and click on the "manage" tab of the organization to edit users and collections. 

### Expected behaviour
Manager user should be able to edit users and collections.

### Actual behaviour
As soon as you click, you are logged out.

### Troubleshooting data
Logged out as soon as you click on the "manage" tab:
![Captura de pantalla de 2022-01-17 12-25-48](https://user-images.githubusercontent.com/2324630/149765853-9c3d9728-f993-40c2-b460-26277e43b6bb.png)

Some logs:
```
[2022-01-17 12:25:38.696][vaultwarden::api::identity][INFO] User xxxxx@yyy.zzz logged in successfully. IP: X.X.X.X
[2022-01-17 12:25:38.696][response][INFO] POST /identity/connect/token (login) => 200 OK
[2022-01-17 12:25:38.733][parity_ws::io][INFO] Accepted a new tcp connection from 172.18.0.2:45014.
[2022-01-17 12:25:38.763][request][INFO] POST /identity/connect/token
[2022-01-17 12:25:38.766][response][INFO] POST /identity/connect/token (login) => 200 OK
[2022-01-17 12:25:38.800][request][INFO] GET /api/sync?excludeDomains=true
[2022-01-17 12:25:38.817][response][INFO] GET /api/sync?<data..> (sync) => 200 OK
[2022-01-17 12:25:39.512][response][INFO] GET /icons/<domain>/icon.png (icon) => 200 OK
[2022-01-17 12:25:39.512][response][INFO] GET /icons/<domain>/icon.png (icon) => 200 OK
[2022-01-17 12:25:47.330][request][INFO] GET /api/collections
[2022-01-17 12:25:47.330][response][INFO] GET /api/collections (get_user_collections) => 200 OK
[2022-01-17 12:25:47.345][request][INFO] GET /api/organizations/b9cdfd6b-a86a-44bd-abb0-3c8279357127/collections
[2022-01-17 12:25:47.346][auth][ERROR] Unauthorized Error: You need to be Admin or Owner to call this endpoint
[2022-01-17 12:25:47.346][response][INFO] GET /api/organizations/<org_id>/collections (get_org_collections) => 401 Unauthorized
```

**Comment by BlackDex** [comment] 2022-01-17 12:38
Please please search before you post an issue!

Duplicate of #2151 and #2227 and #2233
And already fixed in #2169 

Use the `testing` tagged image for this fix.

**Closed by BlackDex** 2022-01-17 12:38 UTC
