### ISSUE TITLE
Lost access after update

### ISSUE THREAD

**Issue by siperwrx** [dani-garcia/vaultwarden#2495] opened 2022-05-24 18:39 UTC
### Subject of the issue
I updated to Version 1.25.0 yesterday and now I can't access my vault. It won't accept my master password (which I know is correct). Is it possible to downgrade and restore my passwords? I'm using Docker on Synology.

### Deployment environment

* vaultwarden version: 1.25.0 

* Install method: Docker image

* Clients used:  Brave extension, Android, web

* Reverse proxy and version: 

* MySQL/MariaDB or PostgreSQL version: 

* Other relevant details:

**Comment by siperwrx** [comment] 2022-05-24 18:40
This is the last line of the log after updating:
[2022-05-23 21:24:29.377][response][INFO] (login) POST /identity/connect/token => 400 Bad Request

For follow up attempts to login, I'm getting the same error.

**Comment by BlackDex** [comment] 2022-05-24 18:57
Looks like a duplicate of #2493

**Comment by Tieneks** [comment] 2022-05-24 19:42
Could you answer the three questions mentioned [here](https://github.com/dani-garcia/vaultwarden/discussions/2493#discussioncomment-2814128)?

**Comment by BlackDex** [comment] 2022-05-24 20:18
Closed as a duplicate of #2493.

**Closed by BlackDex** 2022-05-24 20:18 UTC
