### ISSUE TITLE
Instant logoff when managing organisation with usertype "manager"

### ISSUE THREAD

**Issue by C0m4xy** [dani-garcia/vaultwarden#2189] opened 2021-12-30 08:56 UTC
Hi,

I´ve created an new organisation and invited an user with role "manager".
When this user tries to manage the organisation, he/she will instantly logged off from vaultwarden.

can anyone else reproduce this bug?

Kind Regards

![image](https://user-images.githubusercontent.com/96548927/147736533-99963c78-a717-4dcf-8ee8-e7d8e56f4800.png)
![image](https://user-images.githubusercontent.com/96548927/147736545-e5ab6f4f-eb35-47bb-a85c-3ffb25af0bc2.png)

Versions
Server Installed 1.23.1
Web Installed 2.25.0
Database SQLite: 3.35.4

**Comment by BlackDex** [comment] 2021-12-30 08:58
Duplicate of #2151 fixed via #2169

**Closed by BlackDex** 2021-12-30 08:58 UTC
