### ISSUE TITLE
Can't connect to database

### ISSUE THREAD

**Issue by KBCACheia** [dani-garcia/vaultwarden#2132] opened 2021-12-04 19:47 UTC
After a restart the vaultwarden can't connect the database. And i get this message.

"[vaultwarden::util][WARN] Can't connect to database, retrying: Failed to create pool. 
[CAUSE] Error (
       None,
)"

### Deployment environment

Debian 10
Docker
DB: PostgreSQL
Version: 1.23.0

**Comment by BlackDex** [comment] 2021-12-04 20:03
Duplicate of #2134

**Closed by BlackDex** 2021-12-04 20:03 UTC
