### ISSUE TITLE
Bug: importing password history

### ISSUE THREAD

**Issue by MakeCartWheel** [dani-garcia/vaultwarden#4278] opened 2024-01-27 20:11 UTC
### Broken Importing password history from vaultwarden export file
moving from one instance of vaultwarden to other, after exporting from one and importing to another, there is no password history

### Steps to reproduce
1) export from vaultwarden (json)
2) import file to another vaultwarden with "bitwarden json"
3) in item details missing "password history"

### Expected behaviour
password histroy should be imported correctly
(i see password history details in json files, so problem in importing)

### environment (Generated via diagnostics page)
* Vaultwarden version: v1.30.1
* Web-vault version: v2023.10.0
* OS/Arch: linux/x86_64
* Running within Docker: true (Base: Debian)
* Environment settings overridden: true
* Uses a reverse proxy: true
* IP Header check: true (X-Real-IP)
* Internet access: true
* Internet access via a proxy: false
* DNS Check: true
* Browser/Server Time Check: true
* Server/NTP Time Check: true
* Domain Configuration Check: true
* HTTPS Check: true
* Database type: SQLite
* Database version: 3.44.0
* Clients used: 
* Reverse proxy and version: 
* Other relevant information: 

### Config (Generated via diagnostics page)
<details><summary>Show Running Config</summary>

**Environment settings which are overridden:** SIGNUPS_ALLOWED, SHOW_PASSWORD_HINT, ADMIN_TOKEN

```json
{
  "_duo_akey": null,
  "_enable_duo": false,
  "_enable_email_2fa": false,
  "_enable_smtp": true,
  "_enable_yubico": true,
  "_icon_service_csp": "",
  "_icon_service_url": "",
  "_ip_header_enabled": true,
  "_smtp_img_src": "cid:",
  "admin_ratelimit_max_burst": 3,
  "admin_ratelimit_seconds": 300,
  "admin_session_lifetime": 20,
  "admin_token": "***",
  "allowed_iframe_ancestors": "",
  "attachments_folder": "data/attachments",
  "auth_request_purge_schedule": "30 * * * * *",
  "authenticator_disable_time_drift": false,
  "data_folder": "data",
  "database_conn_init": "",
  "database_max_conns": 10,
  "database_timeout": 30,
  "database_url": "***************",
  "db_connection_retries": 15,
  "disable_2fa_remember": false,
  "disable_admin_token": false,
  "disable_icon_download": false,
  "domain": "*****://********************",
  "domain_origin": "*****://********************",
  "domain_path": "",
  "domain_set": true,
  "duo_host": null,
  "duo_ikey": null,
  "duo_skey": null,
  "email_attempts_limit": 3,
  "email_change_allowed": true,
  "email_expiration_time": 600,
  "email_token_size": 6,
  "emergency_access_allowed": true,
  "emergency_notification_reminder_schedule": "0 3 * * * *",
  "emergency_request_timeout_schedule": "0 7 * * * *",
  "enable_db_wal": true,
  "event_cleanup_schedule": "0 10 0 * * *",
  "events_days_retain": null,
  "extended_logging": true,
  "helo_name": "***************",
  "hibp_api_key": null,
  "icon_blacklist_non_global_ips": true,
  "icon_blacklist_regex": null,
  "icon_cache_folder": "data/icon_cache",
  "icon_cache_negttl": 259200,
  "icon_cache_ttl": 2592000,
  "icon_download_timeout": 10,
  "icon_redirect_code": 302,
  "icon_service": "internal",
  "incomplete_2fa_schedule": "30 * * * * *",
  "incomplete_2fa_time_limit": 3,
  "invitation_expiration_hours": 120,
  "invitation_org_name": "Vaultwarden",
  "invitations_allowed": true,
  "ip_header": "X-Real-IP",
  "job_poll_interval_ms": 30000,
  "log_file": "/data/vaultwarden.log",
  "log_level": "warn",
  "log_timestamp_format": "%Y-%m-%d %H:%M:%S.%3f",
  "login_ratelimit_max_burst": 10,
  "login_ratelimit_seconds": 60,
  "org_attachment_limit": null,
  "org_creation_users": "",
  "org_events_enabled": false,
  "org_groups_enabled": false,
  "password_hints_allowed": true,
  "password_iterations": 300000,
  "push_enabled": false,
  "push_installation_id": "***",
  "push_installation_key": "***",
  "push_relay_uri": "https://push.bitwarden.com",
  "reload_templates": false,
  "require_device_email": false,
  "rsa_key_filename": "data/rsa_key",
  "send_purge_schedule": "0 5 * * * *",
  "sendmail_command": null,
  "sends_allowed": true,
  "sends_folder": "data/sends",
  "show_password_hint": false,
  "signups_allowed": false,
  "signups_domains_whitelist": "",
  "signups_verify": false,
  "signups_verify_resend_limit": 6,
  "signups_verify_resend_time": 3600,
  "smtp_accept_invalid_certs": false,
  "smtp_accept_invalid_hostnames": false,
  "smtp_auth_mechanism": null,
  "smtp_debug": false,
  "smtp_embed_images": true,
  "smtp_explicit_tls": null,
  "smtp_from": "*********************",
  "smtp_from_name": "Vaultwarden",
  "smtp_host": "**********",
  "smtp_password": null,
  "smtp_port": 25,
  "smtp_security": "off",
  "smtp_ssl": null,
  "smtp_timeout": 15,
  "smtp_username": null,
  "templates_folder": "data/templates",
  "tmp_folder": "data/tmp",
  "trash_auto_delete_days": null,
  "trash_purge_schedule": "0 5 0 * * *",
  "use_sendmail": false,
  "use_syslog": false,
  "user_attachment_limit": null,
  "web_vault_enabled": true,
  "web_vault_folder": "web-vault/",
  "websocket_address": "0.0.0.0",
  "websocket_enabled": true,
  "websocket_port": 3012,
  "yubico_client_id": null,
  "yubico_secret_key": null,
  "yubico_server": null
}
```
</details>

**Comment by BlackDex** [comment] 2024-01-27 21:33
I just tested it, and it works fine for me. It imports the history just fine.
CSV files do not contain the history, only the JSON exports.

I also tested the different web-vault versions, but all worked.
So please try it again, and make sure you use the JSON export.

Also, the whole import/export is mostly handled by the clients and not the server. The server just receives multiple vault items which are processed just like a new vault item.

**Comment by BlackDex** [comment] 2024-01-29 07:53
@MakeCartWheel any updates? Only updating your post and removing the CSV part doesn't help.
I have tested it with `latest` and `testing` tagged images, and it work as it should.

Any more details or updates would be helpful. Else i'm going to close this as not reproducible.

**Comment by BlackDex** [comment] 2024-01-30 17:14
I did some more checking, and password history was not imported in web-vaults before v2023.10.0, which correlates to v1.30.0 of Vaultwarden. So all version of Vaultwarden before v1.30.0 are not able to import password history.

According to the Support string you pasted you should have version v1.30.1 and web-vault v2023.10.0, and thus should work.
The only thing i can think of is that either your reverse proxy or your browser servers an older version.

Try to fully refresh the browser, or clear your browser cache, or restart your reverse proxy.

Going to close this as unable to reproduce.

**Closed by BlackDex** 2024-01-30 17:14 UTC

**Comment by MakeCartWheel** [comment] 2024-01-31 16:31
Yeah, sorry about that, I've had busy days.
i will try and response if found something.

**Comment by BlackDex** [comment] 2024-01-31 16:41
No problem, curious if you find something.

**Comment by MakeCartWheel** [comment] 2024-01-31 20:48
I checked it twice, on different versions, everything works perfectly, a week ago my colleague and I were looking at the monitor, not understanding why the history was not transferred. the version was latest (1.30.1), It's some kind of magic. Thanks for your time.

**Comment by BlackDex** [comment] 2024-01-31 21:28
Thanks for checking and reporting back!
