### ISSUE TITLE
can not login with bitwarden android 2024.6.1-beta (11139)

### ISSUE THREAD

**Issue by HalfLike** [dani-garcia/vaultwarden#4680] opened 2024-06-27 08:22 UTC
* vaultwarden version: 1.30.5

* Install method: docker-compose

* Clients used: bitwarden android 2024.6.1-beta (11139)

* Other relevant details:
I can log in normally when using the android relase version, but I cannot log in when I change to the latest kotlin native android beta version. https://github.com/bitwarden/android/releases. The Android client log shows:

BitwardenNetworkClient com...arden.dev D --> POST https://tcqc.run:8043/identity/accounts/prelogin
BitwardenNetworkClient com...arden.dev D {"email":"jdhdhdjdj@qq.com"}

BitwardenNetworkClient com...arden.dev D <-- 200 https://tcqc.run:8043/identity/accounts/prelogin (43ms)
BitwardenNetworkClient com...arden.dev D {"Kdf":0,"KdfIterations":600000,"KdfMemory":null,"KdfParallelism":null}

**Comment by BlackDex** [comment] 2024-06-27 09:03
Duplicate of #4656 and already resolved via `testing` tagged images.

**Closed by BlackDex** 2024-06-27 09:03 UTC
